---
- name: updating my inventory
  hosts: localhost
  connection: local

  tasks:
  - name: create an inventory
    shell: "tower-cli inventory create -n 'Static inventory' --organization Default"
    register: inventory_output

  - debug: var=inventory_output


  - name: find project directory
    find:
      paths: "/var/lib/awx/projects"
      file_type: directory
      patterns: "*inventory"
    register: find_output

    - block:
       - name: import static inventory file if new inventory
         shell: "tower-manage inventory_import --source={{find_output.files[0].path}}/hosts.ini --inventory-id={{inventory_output.stdout.split('\n')[4].split(' ')[0]}}"
      rescue:
       - name: import static inventory file if overwriting
         shell: "tower-manage inventory_import --source={{find_output.files[0].path}}/hosts.ini --inventory-id={{inventory_output.stdout.split('\n')[4].split(' ')[0]}} --overwrite"
    

  